[project]
name = "astra-claude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "fastmcp>=2.11.3",
    "itsdangerous>=2.2.0",
    "mcp[cli]>=1.13.1",
]
